#!/bin/sh

if ! type commitlint >/dev/null 2>/dev/null; then
	echo ""
    echo "commitlint could not be found"
    echo "installing commitlint..."
    go install github.com/conventionalcommit/commitlint@latest
	echo ""
	echo "Retry commiting"
    exit 2;
fi

commitlint lint --config githooks/.commitlint.yaml --message $1
