#!/bin/sh

if ! type gitleaks >/dev/null 2>/dev/null; then
	echo ""
    echo "gitleaks could not be found"
    echo "installing gitleaks..."
    go install github.com/zricethezav/gitleaks/v8@latest
	echo ""
	echo "Retry commiting"
    exit 2;
fi

gitleaks protect --verbose --redact --staged